server:
  port: 8000

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DeskbookDev;encrypt=false;
    username: sa
    password: Ronak@123
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
  